news_sites:
  eluniversal:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links = '.titulo '
  elpais:
    url: https://www.elpais.com/mexico
    queries:
      hompage_article_links = '.c_t'