# Output path relative to working directory
output_path: output
news_sites:
  eluniversal:
    parser: ElUniversalParser
    url: https://www.eluniversal.com
    queries:
      homepage_article_links: '.title '
      news_title: '.title '
      news_summary: '.sum '
      news_body: '.note-text '
#  elpais:
#    parser: ElPaisParser
#    url: https://www.elpais.com/mexico
#    queries:
#      hompage_article_links: '.c_t'